server:
  port: 8083

spring:
  application:
    name: request-service

  datasource:
    url: jdbc:h2:mem:requestdb
    driver-class-name: org.h2.Driver
    username: ibtisam
    password: 1111

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
