server:
  port: 8761 # port on which Eureka server will run

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false # do not register itself as a client
    fetch-registry: false # do not fetch other services
